### PR TITLE
Updating Mapping Guide link for v0.3 of the Mapping Guide 

### PR DESCRIPTION
**Pull request by ehazard-mitre**
This mapping guide updates: JSON-LD examples

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
Also, for reference back to Jira, this PR is addressing ONT-261.

**Comment by ehazard-mitre** [comment]
Thanks for the feedback @ajnelson-nist , I've made updates to the document and will be issuing a new PR. Regarding each of your feedback bullets: 

1. I've now changed it to July for version 3 of this document
2. I've cut out any references to `fileSystemType`
3. Updated "Trace" to "case-core:Trace"
4. Updated all instances of `@type` to include the prefix in it's value (`ContentData `--> `uco-observable:ContentData`)
5. Thanks for pointing this out, I was not aware of this - I believe the only example of this in this document is in the Hash example, so I've simply just copied the example from Asgard 
6. Fixed the typo

**Comment by ehazard-mitre** [comment]
Turns out, I don't need to make a new PR. This PR still works because the document link hasn't changed, only the content of the document. 

@ajnelson-nist , could you review again?

**Comment by ajnelson-nist** [comment]
I just looked over the document's JSON, and found a few minor things.  I added edits as suggested changes.  Once you accept those changes, this passes my review.

**Pull request merged**
