### PR TITLE
Updated MSISDN

### PR DESCRIPTION
**Pull request by eoghanscasey**
Updated MSISDN representation.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
@eoghanscasey , thanks for these updates!  The Asgard example is one of the examples that uses snippets, so these updates should be done in the `/examples/asgard/src/` directory.

**Comment by ajnelson-nist** [comment]
This PR's branch should merge in #202 and address the newly raised SHACL validation errors.

**Comment by ajnelson-nist** [comment]
`kb:lge-device-eee670c6-01d4-4e42-bb6b-ebeca149b168` (in `/examples/owl_trafficking/`) is a `observable:Device` that has a `MobileAccountFacet`.  I've made this point several times recently---most recently [here](https://github.com/ucoProject/UCO/issues/438#issuecomment-1228788603)---but because [UCO Issue 361](https://github.com/ucoProject/UCO/issues/361) is trying to dissuade this node association, can you please shift the `MSISDN` over to an appropriate `Account` object?

**Review by ajnelson-nist — CHANGES_REQUESTED** [review]
`kb:lge-device-eee670c6-01d4-4e42-bb6b-ebeca149b168` in the `owl_trafficking` narrative should also have its `MSISDN` usage moved from the `Device` object to an `Account` object.

**Comment by eoghanscasey** [comment]
Made updates in the /examples/asgard/src/ directory and make regenerated the example.

**Review by kchason — APPROVED** [review]

**Review by ajnelson-nist — APPROVED** [review]

**Pull request merged**
